Repository containers/conmon-rs, pull requests merged in 2022-11, with the labels that each got.

#868 Bump to v0.4.0
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/documentation, lgtm, release-note-none

#870 Fix the link in README.md
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#886 Add usage/release documentation
  README.md
  conmon-rs/server/src/lib.rs
  release.md
  usage.md
Labels: approved, kind/documentation, lgtm, release-note

#898 rust: Port client to use tokio too
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/client/src/main.rs
Labels: approved, lgtm, release-note-none
