Repository containers/conmon-rs, pull requests merged in 2022-08, with the labels that each got.

#569 Simplify attach handling
  conmon-rs/server/src/attach.rs
  conmon-rs/server/src/container_io.rs
  conmon-rs/server/src/rpc.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#577 Pin `containers/*` dependencies
  go.mod
  go.sum
  pkg/client/suite_test.go
Labels: approved, kind/dependency-change, lgtm, release-note-none

#589 add release packaging
  .github/workflows/release.yml
  .gitignore
  Cargo.lock
  Makefile
  conmon-rs/server/Cargo.toml
  conmon-rs/server/src/main.rs
Labels: approved, lgtm, release-note-none

#594 add dollar sign to release.yml
  .github/workflows/release.yml
Labels: approved, do-not-merge/release-note-label-needed

#596 add branch-name action
  .github/workflows/release.yml
Labels: approved, do-not-merge/release-note-label-needed

#597 add slash to prefix
  Makefile
Labels: approved, do-not-merge/release-note-label-needed

#588 Add cleanup process
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/child.rs
  conmon-rs/server/src/child_reaper.rs
  conmon-rs/server/src/rpc.rs
  internal/proto/conmon.capnp.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/suite_test.go
Labels: approved, kind/feature, lgtm, release-note

#598 fixes for packaging
  Makefile
  conmon-rs/server/Cargo.toml
Labels: approved, do-not-merge/release-note-label-needed

#599 add install target
  Makefile
Labels: approved, do-not-merge/release-note-label-needed

#601 add prefix to Makefile
  Makefile
Labels: approved, do-not-merge/release-note-label-needed

#602 Autobuild Copr RPM after every PR merge
  Makefile
  conmon-rs.spec.rpkg
Labels: approved, kind/other, lgtm, release-note-none

#604 fix s390x and armhfp builds
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, release-note

#605 use arm
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, do-not-merge/release-note-label-needed

#607 Downgrade anyhow to fix gh-pages build
  conmon-rs/server/Cargo.toml
Labels: approved, kind/ci, lgtm, release-note-none

#610 bump capnproto to alpha.5
  go.mod
  go.sum
  internal/proto/conmon.capnp.go
  pkg/client/attach.go
  pkg/client/client.go
Labels: approved, lgtm, release-note-none

#654 Update golangci-lint and config
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  pkg/client/attach.go
  pkg/client/suite_test.go
Labels: approved, kind/ci, lgtm, release-note-none

#652 add support for {Global,Command}Args in CreateContainer
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/server.rs
  internal/proto/conmon.capnp.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/suite_test.go
Labels: approved, kind/feature, lgtm, release-note

#655 Fix rust docs link
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#672 Add listener unit tests
  conmon-rs/server/src/attach.rs
  conmon-rs/server/src/listener.rs
  conmon-rs/server/src/server.rs
  conmon-rs/server/src/terminal.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#674 Run unit tests
  .github/workflows/ci.yml
  conmon-rs/server/src/terminal.rs
Labels: approved, kind/failing-test, lgtm, release-note-none
