Repository containers/conmon-rs, pull requests merged in 2022-09, with the labels that each got.

#681 Add streams unit test
  conmon-rs/server/src/container_io.rs
  conmon-rs/server/src/streams.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#676 Add copr badge to link packages
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#679 Bump to v0.2.0
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#688 Fix 32bit build
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, kind/ci, lgtm, release-note-none

#692 Make oom watcher errors more verbose
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#683 cancel I/O (notably attach) when container exits
  Makefile
  conmon-rs/server/src/attach.rs
  conmon-rs/server/src/child.rs
  conmon-rs/server/src/child_reaper.rs
  conmon-rs/server/src/container_io.rs
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/streams.rs
  conmon-rs/server/src/terminal.rs
  pkg/client/attach.go
  pkg/client/client_test.go
  pkg/client/suite_test.go
Labels: approved, kind/bug, lgtm, release-note

#690 Add memory leak integration test for Exec Sync
  pkg/client/client_test.go
Labels: approved, kind/bug, lgtm, release-note-none

#698 Allow missing OOM watcher cgroup paths
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#699 Remove resolved TODO FIXME
  conmon-rs/server/src/rpc.rs
Labels: approved, kind/documentation, lgtm, release-note-none

#694 Close attach readers
  go.mod
  go.sum
  pkg/client/attach.go
  pkg/client/client.go
  pkg/client/suite_test.go
Labels: approved, kind/bug, lgtm, release-note

#701 make: add TEST_FLAGS to ginkgo tests
  Makefile
Labels: approved, kind/ci, lgtm, release-note-none

#700 attach: use Message::Done instead of cancellation token
  conmon-rs/server/src/attach.rs
  conmon-rs/server/src/container_io.rs
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/streams.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#704 Reduce memory usage for attach
  Cargo.toml
  conmon-rs/server/src/attach.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#707 Allow verbose version output
  .golangci.yml
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/config.rs
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/server.rs
  conmon-rs/server/src/version.rs
  internal/proto/conmon.capnp.go
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, kind/feature, lgtm, release-note

#712 Allow having multiple attach sessions in parallel
  conmon-rs/server/src/attach.rs
Labels: approved, kind/feature, lgtm, release-note

#702 Fix critest "runtime should support attach" test
  conmon-rs/server/src/attach.rs
Labels: approved, kind/bug, lgtm, release-note

#719 Udpate clap to v3.2.21
  Cargo.lock
  conmon-rs/server/Cargo.toml
  conmon-rs/server/src/config.rs
Labels: approved, kind/dependency-change, lgtm, release-note-none

#703 Add critest run to CI
  .github/setup
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none

#717 Fix server shutdown if conmon-rs got manually killed
  pkg/client/client.go
Labels: approved, kind/bug, lgtm, release-note

#718 Remove attach socket path if not in use
  pkg/client/attach.go
  pkg/client/client.go
Labels: approved, kind/feature, lgtm, release-note

#725 release: add 'v' to the release tag
  Makefile
Labels: approved, kind/other, lgtm, release-note

#724 Build with 1.58.1
  .github/workflows/ci.yml
  .github/workflows/cross.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Makefile
  conmon-rs/server/Cargo.toml
Labels: approved, kind/dependency-change, lgtm, release-note

#726 bump to v0.3.0
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/other, lgtm, release-note-none

#727 release: fix location of v
  Makefile
Labels: approved, kind/other, lgtm, release-note-none

#734 Send only streams data if channel is not closed
  conmon-rs/server/src/container_io.rs
Labels: approved, kind/bug, lgtm, release-note

#739 Remove token from ContainerIO read_loop
  conmon-rs/server/src/container_io.rs
  conmon-rs/server/src/streams.rs
  conmon-rs/server/src/terminal.rs
  pkg/client/client_test.go
Labels: approved, kind/bug, lgtm, release-note

#746 Read once again after stdin token cancelled
  conmon-rs/server/src/attach.rs
  conmon-rs/server/src/container_io.rs
  pkg/client/attach.go
Labels: approved, kind/bug, lgtm, release-note

#749 Re-enable critest GitHub action
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none

#751 Add support for leaving stdin open on attach
  .github/workflows/ci.yml
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/attach.rs
  conmon-rs/server/src/rpc.rs
  internal/proto/conmon.capnp.go
  pkg/client/attach.go
  pkg/client/client_test.go
Labels: approved, kind/feature, lgtm, release-note

#754 Re-enable critest GitHub action
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none
