Repository containers/conmon-rs, pull requests merged in 2023-09, with the labels that each got.

#1661 Bump to 0.6.0
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#1664 Fix get script for tags
  .github/create-marker
  scripts/get
Labels: approved, kind/bug, lgtm, release-note

#1680 Add nix build for multi-arch static binaries
  .github/workflows/ci.yml
  .gitignore
  Makefile
  dependencies.yaml
  nix/default-amd64.nix
  nix/default-arm64.nix
  nix/default-ppc64le.nix
  nix/default.nix
  nix/derivation.nix
  nix/nixpkgs.json
  nix/nixpkgs.nix
  nix/overlay.nix
  nix/static.nix
Labels: approved, kind/feature, lgtm, release-note

#1682 Add architecture support to `get` script
  .github/workflows/ci.yml
  scripts/get
Labels: approved, kind/feature, lgtm, release-note

#1683 Fix constant int overflow for `GOARCH=386`
  pkg/client/remote_fds.go
Labels: approved, kind/bug, lgtm, release-note

#1690 Add -n flag to get script to avoid binary execution
  scripts/get
Labels: approved, kind/feature, lgtm, release-note

#1689 Fix get script architecture
  scripts/get
Labels: approved, kind/cleanup, lgtm, release-note-none

#1684 Bump to v0.6.1
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#1700 Fix loop which never actually loops
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#1699 Create marker only if CI passed
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none

#1708 Bump max rss to 7500
  Makefile
  pkg/client/suite_test.go
Labels: approved, kind/ci, lgtm, release-note-none

#1704 Add checkout to create marker
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none

#1706 Update ginkgo to v2.12.0
  Makefile
  dependencies.yaml
Labels: approved, kind/ci, lgtm, release-note-none

#1713 vendor of containers/common
  go.mod
  go.sum
  pkg/client/attach.go
Labels: approved, lgtm, release-note-none

#1729 Fix clippy lint
  conmon-rs/server/src/pause.rs
  conmon-rs/server/src/version.rs
Labels: approved, kind/ci, lgtm, release-note-none
