Repository containers/conmon-rs, pull requests merged in 2023-06, with the labels that each got.

#1409 Set release build debug flag to `0`
  Cargo.toml
Labels: approved, kind/ci, lgtm, release-note-none

#1441 Remove redundant serialization of OOMExitPaths
  pkg/client/client.go
Labels: approved, kind/bug, lgtm, release-note-none

#1440 Mention that the go client reuses a running server
  pkg/client/client.go
Labels: approved, kind/documentation, lgtm, release-note-none

#1451 COPR: Exclude ELN builds
  .packit.yaml
Labels: approved, kind/other, lgtm, release-note-none

#1454 Packit: Fix Copr target
  .packit.yaml
Labels: approved, kind/other, lgtm, release-note-none
