Repository containers/conmon-rs, pull requests merged in 2023-02, with the labels that each got.

#1071 Update golangci-lint and config
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
Labels: approved, kind/ci, lgtm, release-note-none

#1072 Switch to go 1.19 in CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: approved, kind/ci, lgtm, release-note-none

#1073 Use zeitgeist for dependency verification
  .github/workflows/ci.yml
  Makefile
  dependencies.yaml
Labels: approved, kind/ci, lgtm, release-note-none

#1074 Switch to go 1.20 for CI jobs
  .github/workflows/ci.yml
  .github/workflows/release.yml
  dependencies.yaml
Labels: approved, kind/ci, lgtm, release-note-none

#1067 Mimic pinns namespace path layout
  .golangci.yml
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/config.rs
  conmon-rs/server/src/pause.rs
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/server.rs
  internal/proto/conmon.capnp.go
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, kind/feature, lgtm, release-note

#1091 Enable ginkgolint
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  pkg/client/client_test.go
  pkg/client/suite_test.go
Labels: approved, kind/ci, lgtm, release-note-none

#1104 [CI:BUILD] Packit: initial enablement
  .packit.sh
  .packit.yaml
  conmon-rs.spec.rpkg
  conmon-rs/common/Cargo.toml
Labels: approved, kind/ci, lgtm, release-note-none

#1106 [CI:DOCS] Packit: fix comments
  .packit.sh
  conmon-rs.spec.rpkg
Labels: approved, kind/documentation, lgtm, release-note-none

#1108 Enable packit for `main` branch
  .packit.yaml
Labels: approved, kind/ci, lgtm, release-note-none

#1110 [CI:DOCS] Packit: include ref to main branch builds
  .packit.yaml
Labels: approved, kind/documentation, lgtm, release-note-none

#1112 [CI:DOCS] nit: fix typo
  conmon-rs/server/src/pause.rs
Labels: approved, kind/other, lgtm, release-note-none
