Repository containers/conmon-rs, pull requests merged in 2023-07, with the labels that each got.

#1503 Remove unnecessary SetRequest calls
  pkg/client/attach.go
  pkg/client/client.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#1505 Fix forget_grandchild retain condition
  conmon-rs/server/src/child_reaper.rs
Labels: approved, kind/bug, lgtm, release-note-none

#1498 Use capnp map for tracing metadata
  Cargo.lock
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/Cargo.toml
  conmon-rs/server/src/capnp_util.rs
  conmon-rs/server/src/child_reaper.rs
  conmon-rs/server/src/lib.rs
  conmon-rs/server/src/telemetry.rs
  internal/proto/conmon.capnp.go
  pkg/client/attach.go
  pkg/client/capnp_util.go
  pkg/client/client.go
Labels: approved, kind/other, lgtm, release-note-none

#1499 Create container with environment variables
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/child_reaper.rs
  conmon-rs/server/src/rpc.rs
  internal/proto/conmon.capnp.go
  pkg/client/client.go
Labels: approved, kind/feature, lgtm, release-note

#1449 Update clap to v4.3.8
  Cargo.lock
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#1504 Add per command cgroup manager option
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/src/config.rs
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/server.rs
  internal/proto/conmon.capnp.go
  pkg/client/client.go
  pkg/client/consts.go
Labels: approved, kind/feature, lgtm, release-note
