Repository containers/conmon-rs, pull requests merged in 2023-03, with the labels that each got.

#1153 Use default umask `0022`
  conmon-rs/server/src/init.rs
  conmon-rs/server/src/server.rs
Labels: approved, kind/feature, lgtm, release-note

#1154 Fix signing binary
  .github/workflows/ci.yml
Labels: approved, kind/failing-test, lgtm, release-note-none

#1166 Update Cap'n Proto to v0.14.11
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/dependency-change, lgtm, release-note-none

#1174 Packit: Fix sed for release tag update in rpm spec
  .packit.sh
Labels: approved, kind/other, lgtm, release-note-none

#1195 Bump to v0.5.1
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/feature, lgtm, release-note-none

#1217 Add logo to README.md
  .github/logo/conmon-rs-frameless.png
  .github/logo/conmon-rs.png
  .github/logo/conmon-rs.svg
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#1230 Update zeitgeist to v0.4.1
  Makefile
  dependencies.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none
