Repository containers/conmon-rs, pull requests merged in 2023-08, with the labels that each got.

#1566 packit: Build PRs into default packit COPRs
  .packit.yaml
Labels: approved, kind/failing-test, lgtm, release-note-none

#1562 Fix clippy lint
  conmon-rs/server/src/container_io.rs
Labels: approved, kind/failing-test, lgtm, release-note-none

#1567 Bump Rust to v1.69.0
  .github/workflows/ci.yml
  .github/workflows/release.yml
  conmon-rs/server/Cargo.toml
  dependencies.yaml
Labels: approved, kind/ci, lgtm, release-note

#1568 Add opentelemetry dependency group
  .github/dependabot.yml
Labels: approved, kind/ci, lgtm, release-note-none

#1577 Update ginkgo to v2.11.0
  Makefile
  dependencies.yaml
Labels: approved, kind/ci, lgtm, release-note-none

#1553 Add support for file descriptor passing
  .github/typos.toml
  .github/workflows/ci.yml
  Cargo.lock
  Makefile
  conmon-rs/common/proto/conmon.capnp
  conmon-rs/server/Cargo.toml
  conmon-rs/server/src/child_reaper.rs
  conmon-rs/server/src/config.rs
  conmon-rs/server/src/fd_socket.rs
  conmon-rs/server/src/lib.rs
  conmon-rs/server/src/listener.rs
  conmon-rs/server/src/macros.rs
  conmon-rs/server/src/rpc.rs
  conmon-rs/server/src/server.rs
  internal/proto/conmon.capnp.go
  pkg/client/capnp_util.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/remote_fds.go
  pkg/client/suite_test.go
Labels: approved, kind/feature, lgtm, release-note

#1595 Change resize channel to receive only
  pkg/client/attach.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#1596 Update golangci-lint to v1.54.1
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  go.mod
  go.sum
  pkg/client/attach.go
  pkg/client/remote_fds.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#1655 Fix early stdio close due to multiple ownership
  Cargo.lock
  conmon-rs/server/Cargo.toml
  conmon-rs/server/src/container_io.rs
  conmon-rs/server/src/streams.rs
  conmon-rs/server/src/terminal.rs
Labels: approved, kind/bug, lgtm, release-note-none
