Repository containers/conmon-rs, pull requests merged in 2024-08, with the labels that each got.

#2353 Fix OOM slice removal race
  conmon-rs/server/src/oom_watcher.rs
Labels: approved, kind/bug, lgtm, release-note

#2350 Update nixpkgs
  nix/nixpkgs.json
Labels: approved, kind/dependency-change, lgtm, release-note-none

#2361 Fix borrowed expression which implements trait
  conmon-rs/server/src/rpc.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#2352 Bump to v0.6.4
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#2366 Add `gitMinimal` nix build dependency
  nix/default-s390x.nix
  nix/derivation.nix
Labels: approved, kind/ci, lgtm, release-note

#2376 Bump to v0.6.5
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#2382 Chown cache before installing ginkgo
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none

#2383 Remove double vendored sources from release
  Makefile
  release.md
Labels: approved, kind/cleanup, lgtm, release-note-none

#2385 Disable dependabot for Rust
  .github/dependabot.yml
Labels: approved, kind/ci, lgtm, release-note-none

#2384 Don’t generate lockfile for gh-pages workflow
  .github/workflows/gh-pages.yml
Labels: approved, kind/ci, lgtm, release-note-none

#2388 Add cargo dependency update job
  .github/workflows/cargo-upgrade.yml
  .gitignore
Labels: approved, kind/ci, lgtm, release-note-none

#2390 Don't run `cargo update`
  .github/workflows/cargo-upgrade.yml
Labels: approved, kind/ci, lgtm, release-note-none

#2351 Add CRI-O OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, kind/cleanup, lgtm, release-note-none

#2391 Change default from localhost to 127.0.0.1
  conmon-rs/server/src/config.rs
  pkg/client/client.go
Labels: approved, kind/other, lgtm, release-note
