Repository containers/conmon-rs, pull requests merged in 2024-07, with the labels that each got.

#2312 Use `.gitignore` in nix build excludes
  nix/derivation.nix
Labels: approved, kind/ci, lgtm, release-note-none

#2306 Update golangci-lint and fix lints
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  pkg/client/capnp_util.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/remote_fds.go
  pkg/client/suite_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#2317 Update go-capnp package to fix build issue on Go 1.23
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Makefile
  go.mod
  go.sum
  pkg/client/client.go
Labels: approved, kind/dependency-change, lgtm, release-note-none
