Repository containers/conmon-rs, pull requests merged in 2024-09, with the labels that each got.

#2401 Add support for crun `--log-level`
  conmon-rs/server/src/server.rs
Labels: approved, kind/feature, lgtm, release-note

#2403 Switch to go 1.23
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  go.mod
  pkg/client/suite_test.go
Labels: approved, kind/dependency-change, lgtm, release-note-none

#2405 Add prettier CI target
  .github/dependabot.yml
  .github/workflows/cargo-upgrade.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .golangci.yml
  .prettierignore
  Makefile
Labels: approved, kind/ci, lgtm, release-note-none

#2406 Pin GitHub actions dependencies
  .github/workflows/cargo-upgrade.yml
  .github/workflows/ci.yml
  .github/workflows/cross.yml
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
Labels: approved, kind/ci, lgtm, release-note-none

#2409 Add support for `make help`
  Makefile
Labels: approved, kind/cleanup, lgtm, release-note-none

#2415 Run waitpid on childs to ensure no zombies are left behind
  conmon-rs/server/src/child_reaper.rs
Labels: approved, kind/bug, lgtm, release-note

#2413 Print child ID and error if command failed
  conmon-rs/server/src/child_reaper.rs
Labels: approved, kind/cleanup, lgtm, release-note-none

#2416 Bump to v0.6.6
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/cleanup, lgtm, release-note-none

#2417 ci: checkout before go setup
  .github/workflows/ci.yml
Labels: approved, kind/ci, lgtm, release-note-none

#2418 Switch to latest `nightly` toolchain
  .github/workflows/ci.yml
  dependencies.yaml
Labels: approved, kind/ci, lgtm, release-note-none

#2429 packit: remove f39
  .packit.yaml
Labels: approved, kind/failing-test, lgtm, release-note-none

#2423 Replace actions-rs GitHub actions
  .github/workflows/cargo-upgrade.yml
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
Labels: approved, kind/ci, lgtm, release-note-none
