Repository containers/conmon-rs, pull requests merged in 2025-07, with the labels that each got.

#2588 Bump version to v0.7.0
  Cargo.lock
  conmon-rs/client/Cargo.toml
  conmon-rs/common/Cargo.toml
  conmon-rs/server/Cargo.toml
Labels: approved, kind/ci, release-note-none

#2592 Add @bitoku as reviewer
  OWNERS_ALIASES
Labels: approved, kind/other, lgtm, release-note-none

#2589 Add `--version-json` flag for JSON version output
  conmon-rs/server/src/config.rs
  conmon-rs/server/src/server.rs
  conmon-rs/server/src/version.rs
Labels: approved, kind/feature, release-note-none

#2598 Fix clippy lints
  conmon-rs/common/src/lib.rs
Labels: approved, kind/ci, lgtm, release-note-none

#2595 Add server `Version()` client API
  pkg/client/client.go
Labels: approved, kind/feature, lgtm, release-note

#2614 Update nixpkgs and nix
  .github/workflows/ci.yml
  dependencies.yaml
  nix/nixpkgs.json
Labels: approved, kind/ci, release-note-none

#2627 Add GITHUB_TOKEN env support to get script
  scripts/get
Labels: approved, kind/ci, lgtm, release-note
